fos_rest:
    disable_csrf_role:    null
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }  
    body_listener:
        enabled: true 